
--Q1. What is the total revenue generated by male vs female customers?
 select gender,
 sum(purchase_amount) as total_revenue
 from customer_data
 group by gender

 --Q2. Which customers used a discount but still spent more than the average purchase amount?
 select customer_id,purchase_amount 
 from customer_data
 where discount_applied='Yes' and purchase_amount>(select avg(purchase_amount) from customer_data)

--Q3.Which are the top 5 products with the highest average review rating?
 select distinct
 top 5  item_purchased ,round(avg(review_rating ),2) as avg_rating
 from customer_data
 group by item_purchased
 order by round(avg(review_rating ),2)  desc

 --Q4.Compare the average purchase amounts between standard and express shipping
 select shipping_type,avg(purchase_amount) as avg_amount
 from customer_data
 where shipping_type in ('Standard','Express')
 group by shipping_type

--Q5.Do subscribed customers spend more?Compare spend and total revenue 
-- between subscribers and non-subscribers
 select subscription_status,
 count(customer_id) as total_customers,
 round(avg(purchase_amount),2) as average_spend,
 round(sum(purchase_amount),2) as total_revenue
 from customer_data
 group by subscription_status
 order by total_revenue

 --Q6.Which 5 products have the highest percentage of purchases with discounts applied?
 select top 5 item_purchased,cast(sum (case when discount_applied='Yes' then 1 else 0 end )*100.0/ count(*) as decimal(5,2)) as percent_discount
 from customer_data
 group by item_purchased
 order by percent_discount desc

 --Q7.Segment customers into new ,returning and loyal based on their total 
 --number of previous purchases and show the count of each segment
with cte as ( select customer_id,previous_purchases ,(case when previous_purchases >10 then 'Loyal'
                         when  previous_purchases >2 then 'Returning'
                         else 'New'
                         end)as customer_segment
from customer_data)
select customer_segment ,count(customer_segment) as count_of_segment
from cte 
group by customer_segment

--Q8. What are top 3 most purchased products within each category?
with cte as (select category, item_purchased ,count(item_purchased) as cnt,
row_number() over(partition by category order by count(item_purchased) desc)as rnk
from customer_data
group by category,item_purchased)
select category,item_purchased ,cnt,rnk
from cte
where rnk<4

--Q9.Are customers who are repeat buyers (more than 5 previous purchases ) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer_data
where previous_purchases>5
group by subscription_status

--Q 10. What is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer_data
group by age_group
order by total_revenue desc